### ISSUE TITLE
Compatibility with zio 1.0.4

### ISSUE THREAD

**Issue by rtimush** [zio/interop-cats#282]
Moved from https://github.com/zio/zio/issues/4581.

The following code fails with `java.lang.NoSuchMethodError: zio.clock.package$.$anonfun$currentTime$3(Lscala/Function0;Lzio/Has;)Lzio/ZIO;` with zio 1.0.4 and works with zio 1.0.3:

```scala
import zio._
import zio.clock._
import zio.interop.catz._
import java.util.concurrent._

Runtime.default.unsafeRunSync {
  cats.effect
    .Timer[ZIO[Clock, Any, *]]
    .clock
    .realTime(TimeUnit.MILLISECONDS)
}
```
Dependencies:
```
libraryDependencies ++= Seq(
  "org.typelevel" %% "cats-effect" % "2.3.1",
  "dev.zio" %% "zio" % "1.0.4",
  "dev.zio" %% "zio-interop-cats" % "2.2.0.1",
)
```
Scastie: https://scastie.scala-lang.org/FmuHgKbqSEaoGO96gkMBsA

This happened because of [inlining](https://github.com/zio/interop-cats/blob/master/project/BuildHelper.scala#L42) from `zio.*`. A fix is to not inline from dependencies (https://github.com/zio/interop-cats/pull/281).
